-- This file was generated by the Reassembly Web Development Kit (RWDK)
-- RWDK is an independent project and in no way affiliated with Anisoptera Games.
-- RWDK was written by TTFTCUTS

{
	-- 17903 = {
	-- 	name=_("Eyes of the STARS"),
	-- 	playable=2,
	-- 	start="17903_^3PSR_J1614-223"
	-- 	color0=0x222222,
	-- 	color1=0x761818,
	-- 	explosionColor0=0x980000,
	-- 	explosionColor1=0xe10000,
	-- 	aiflags=AGGRESSIVE|BAD_AIM|DODGES|FLOCKING|FORGIVING|METAMORPHOSIS|RECKLESS|RIPPLE_FIRE|SMART_FIRE|SOCIAL|SPREAD_FIRE|TRACTOR_TRANSIENT|WANDER,
	-- },

	-- 17900 = {
	-- 	name=_("Interstellar NAVY"),
	-- 	start="17900_ULT-零点-级护卫舰",
	-- 	color0=0x8191b1,
	-- 	color1=0x212733,
	-- 	color2=0x586073,
	-- 	primaries=3,
	-- 	aiflags=CAUTIOUS|DODGES|FLOCKING|FORGIVING|METAMORPHOSIS|PEACEFUL|SMART_FIRE|SOCIAL|TRACTOR_TRANSIENT|WANDER,
	-- },
	
	17904 = {
		name=_("Fungi"),
		playable=2,
		start="17904_战菌",
		explosionColor0=0xbdc7c3,
		explosionColor1=0x677c74,
		primaries=0,
		aiflags=AGGRESSIVE|CAUTIOUS|DODGES|FLOCKING|FORGIVING|PEACEFUL|SMART_FIRE|SOCIAL|SPREAD_FIRE|WANDER,
	},
	
		17905 = {
		name=_("Legion"),
		playable=2,
		start="17905_萨蒂安I",
		color0=0x5fead1,
		color1=0x393a3a,
		aiflags=BAD_AIM|FLOCKING|FORGIVING|METAMORPHOSIS|RECKLESS|SOCIAL|WANDER,
	},
	
	    17902 = {
		name=_("Human interstellar United Nations(HIUN)"),
		playable=2,
		start="17902_镧侦查机",
		primaries=3,
		color0=0x767676,
		color1=0x00d6ff,
		color2=0x2e2e2e,
		aiflags=BAD_AIM|CAUTIOUS|FLOCKING|PEACEFUL|SMART_FIRE|WANDER,
	},
	
		17907 = {
		name=_("Shadow of the Void"),
		playable=2,
		primaries=3,
		start="17907_^6虚空毁灭者",
		thrustSFX=1,
		color0=0x3e3e3e,
		color1=0x75677c,
		color2=0xd14fed,
		aiflags=BAD_AIM|CAUTIOUS|PEACEFUL|SMART_FIRE|WANDER,
	},
	
       17901 = {
		name=_("ICE"),
		color0=0x787d92,
		color1=0x9db5c5,
		explosionColor0=0xc1f7ff,
		explosionColor1=0xf8feff,
		aiflags=CAUTIOUS|FORGIVING|HATES_PLANTS|PEACEFUL|SMART_FIRE|SOCIAL|WANDER,
	},
	
	--     17913 = {
	-- 	name=_("Aquatic Plants"),
	-- 	primaries=0,
	-- 	start="17913_^5烛光草",
	-- 	aiflags=AGGRESSIVE|CAUTIOUS|FLOCKING|FORGIVING|HATES_PLANTS|PEACEFUL|RIPPLE_FIRE|SPREAD_FIRE|WANDER|NO_PARENT,
	-- },
	
	-- 	17908 = {
	-- 	name=_("Interstellar joint mining industry(IMI)"),
	-- 	start="17908_^3警戒船",
	-- 	primaries=3,
	-- 	color0=0xe5ca00,
	-- 	color1=0xf0a023,
	-- 	color2=0x828282,
	-- 	aiflags=BAD_AIM|CAUTIOUS|DODGES|FLOCKING|FORGIVING|HATES_PLANTS|METAMORPHOSIS|SOCIAL|SPREAD_FIRE|TRACTOR_TRANSIENT|WANDER,
	-- },
	
		17910 = {
		name=_("Ghost"),
		primaries=2,
		color0=0x656565,
		color1=0xc5c5c5,
		aiflags=CAUTIOUS|DODGES|FORGIVING|METAMORPHOSIS|WANDER,
	},
	
	    17912 = {
		name=_("Adamantite"),
		start="17912_守护者",
		color0=0xd47351,
		color1=0x999999,
		aiflags=AGGRESSIVE|FLOCKING|FORGIVING|METAMORPHOSIS|RECKLESS|SOCIAL|WANDER,
	},
	
		17914 = {
		name=_("Terra"),
		start="17914_^6守护者-火种",
		primaries=3,
		playable=2,
		color0=0x4b220d,
		color1=0x17c47c,
		color2=0x7e8a87,
		aiflags=CAUTIOUS|DODGES|FLOCKING|FORGIVING|METAMORPHOSIS|PEACEFUL|RIPPLE_FIRE|SMART_FIRE|WANDER,
	},
	
		17906 = {
		name=_("Revitalizer"),
		start="17906_拾光者",
		primaries=2,
		playable=2,
		color0=0xe17411,
		color1=0xb3b3b3,
		aiflags=CAUTIOUS|DODGES|FLOCKING|PEACEFUL|SOCIAL|TRACTOR_TRANSIENT|WANDER,
	},
	
		17915 = {
		name=_("Backbones"),
		playable=2,
		start="17915_“锥”战机EXTRA",
		primaries=3,
		color0=0x696969,
		color1=0x02a300,
		color2=0xbbbbbb,
		explosionColor0=0xff7000,
		explosionColor1=0xc5f3fd,
		aiflags=CAUTIOUS|DODGES|FLOCKING|PEACEFUL|WANDER,
	},
	
	17916 = {
		name=_("FXTY100101"),
		playable=2,
		start="17916_^2MILK系统",
		color0=0x5a9085,
		color1=0x0a8d12,
		explosionColor0=0x84ff67,
		explosionColor1=0xdcffd4,
		aiflags=AGGRESSIVE|FLOCKING|FORGIVING|HATES_PLANTS|METAMORPHOSIS|SPREAD_FIRE|WANDER,
	},
	
	-- 17911 = {
	-- 	name=_("Pilgrims"),
	-- 	playable=2,
	-- 	start="17911_^5幻灭之港-光影探查者",
	-- 	primaries=3,
	-- 	color0=0xe1e1e1,
	-- 	color1=0x8d4ede,
	-- 	color2=0x460ca0,
	-- 	explosionColor0=0xb367ff,
	-- 	explosionColor1=0xe967ff,
	-- 	aiflags=BAD_AIM|CAUTIOUS|DODGES|FLOCKING|FORGIVING|PEACEFUL|SMART_FIRE|SOCIAL|WANDER,
	-- },
	
	-- 17918 = {
	-- 	name=_("Leviathan"),
	-- 	playable=2,
	-- 	start="17918_^5海妖-克拉肯^7",
	-- 	primaries=3,
	-- 	color0=0x9a0000,
	-- 	color1=0x00baa7,
	-- 	color2=0x4e4e4e,
	-- 	aiflags=CAUTIOUS|FLOCKING|HATES_PLANTS|RECKLESS|SOCIAL|WANDER,
	-- },
	
	17922 = {
		name=_("Ectoplasm Lairdweller"),
		start="17922_^4巢雏-碎片^7",
		primaries=3,
		explosionColor0=0x0077c8,
		explosionColor1=0xb40000,
		color0=0x0098ff,
		color1=0x1f1f1f,
		color2=0xb40000,
		aiflags=CAUTIOUS|DODGES|FORGIVING|METAMORPHOSIS|PEACEFUL|SMART_FIRE|SOCIAL|WANDER,
	},

	17997 = {
		name=_("^3X-A Hatchery Consciousness^7"),
		--playable=2,
		start="17997_X-A星云改装型",
		primaries=3,
		color0=0xf0f0f0,
		color1=0xff7500,
		color2=0x262626,
		aiflags=AGGRESSIVE|CAUTIOUS|FLOCKING|FORGIVING|METAMORPHOSIS|PEACEFUL|SMART_FIRE|SOCIAL|TRACTOR_TRANSIENT|WANDER,
	},

	179102 = {
		name="...The Punisher",
		primaries=1,
		color0=0x4232c9,
	},

	179103 = {
		name="...00KF",
		primaries=1,
		color0=0x4232c9,
	},

	179101 = {
		name="Center of the universe......",
		primaries=1,
	}

	17998 = {
		name=_("Wind Catcher"),
    	playable=2,
		primaries=3,
		start="17998_丝雀",
		color0=0xededed,
		color1=0xd696ba,
		color2=0xd65799,
		explosionColor0=0xe7b1cf,
    	explosionColor1=0xededed,
		aiflags=DODGES|FLOCKING|METAMORPHOSIS|PEACEFUL|SMART_FIRE|SOCIAL|WANDER,
	},

	17919 = {
		name="^1The Lost Civilization^7",
		playable=2,
		start="",
		primaries=3,
		color0=0x1a285f,
		color1=0x2e5969,
		color2=0xe0e1ce,
		aiflags=AGGRESSIVE|CAUTIOUS|DODGES|FORGIVING|SMART_FIRE|WANDER,
	},

	--17925 = {
	--	name="骸骨",
	--	playable=2,
	--	start="17925_1",
	--	primaries=0,
	--	aiflags=AGGRESSIVE|CAUTIOUS|DODGES|FLOCKING|FORGIVING|HATES_PLANTS|RECKLESS|SMART_FIRE|SOCIAL|WANDER,
	--},
	
	--7357 = {
		--name="测试型零件整合",
		--primaries=0,
	--},

}
