{
    233333,
    group=17903,
    features=TRACTOR|ASSEMBLER|COMMAND|GENERATOR,
    name=_("Nebula aggregation core"),
    blurb=_("It's the core of the ''Eyes of the Stars'' ship. Protect it.\n^1EOS's weapons are high damage, and it has an AI that always rushes and strays at the enemy, which is very lethal to the Iceberg."),
    shape=ISOTRI_72,
    fillColor=0x820a0a,
    fillColor1=0xa12b2b,
    lineColor=0x222222,
    command={
        faction=17903,
    },
    points=7,
    capacity=500,
    generatorCapacityPerSec=125,
    powerCapacity=375,
},

{
    233334,
    group=17903,
    name=_("Matter Group"),
    features=PALETTE,
    blurb=_("Common block"),
    shape=ISOTRI_72,
    fillColor=0xa12b2b,
    fillColor1=0xa81818,
    lineColor=0x222222,
    durability=3,
},

{
    233335,
    group=17903,
    name=_("Matter Group"),
    blurb=_("Common block"),
    shape=ISOTRI_72,
    scale=2,
    fillColor=0xa12b2b,
    fillColor1=0xa81818,
    lineColor=0x222222,
    durability=3,
},

{
    233336,
    group=17903,
    name=_("Matter Group"),
    features=PALETTE,
    blurb=_("Common block"),
    shape=ISOTRI_36,
    scale=1,
    fillColor=0xa12b2b,
    fillColor1=0xa81818,
    lineColor=0x222222,
    durability=3,
},

{
    233337,
    group=17903,
    name=_("Matter Group"),
    blurb=_("Common block"),
    shape=ISOTRI_36,
    scale=2,
    fillColor=0xa12b2b,
    fillColor1=0xa81818,
    lineColor=0x222222,
    durability=3,
},

{
    233338,
    group=17903,
    name=_("Matter Group"),
    features=PALETTE,
    blurb=_("Common block"),
    shape=RHOMBUS_36_144,
    scale=2,
    fillColor=0xa12b2b,
    fillColor1=0xa81818,
    lineColor=0x222222,
    durability=3,
},

{
    233339,
    group=17903,
    name=_("Matter Group"),
    blurb=_("Common block"),
    shape=RHOMBUS_36_144,
    scale=1,
    fillColor=0xa12b2b,
    fillColor1=0xa81818,
    lineColor=0x222222,
    durability=3,
},

{
    233340,
    group=17903,
    name=_("Matter Group"),
    features=PALETTE,
    blurb=_("Common block"),
    shape=RHOMBUS_72_108,
    scale=1,
    fillColor=0xa12b2b,
    fillColor1=0xa81818,
    lineColor=0x222222,
    durability=3,
},

{
    233341,
    group=17903,
    name=_("Matter Group"),
    blurb=_("Common block"),
    shape=RHOMBUS_72_108,
    scale=2,
    fillColor=0xa12b2b,
    fillColor1=0xa81818,
    lineColor=0x222222,
    durability=3,
},

{
    233342,
    group=17903,
    name=_("Matter Group"),
    features=PALETTE,
    blurb=_("Common block"),
    shape=PENTAGON,
    scale=2,
    fillColor=0xa12b2b,
    fillColor1=0xa81818,
    lineColor=0x222222,
    durability=3,
},

{
    233343,
    group=17903,
    name=_("Matter Group"),
    features=PALETTE,
    blurb=_("Common block"),
    shape=PENTAGON,
    scale=1,
    fillColor=0xa12b2b,
    fillColor1=0xa81818,
    lineColor=0x222222,
    durability=3,
},

{
    233344,
    group=17903,
    name=_("Matter Group"),
    features=PALETTE,
    blurb=_("Common block"),
    shape=PENTAGON,
    scale=1,
    fillColor=0x222222,
    fillColor1=0x161515,
    lineColor=0x820a0a,
    durability=3,
},

{
    233345,
    group=17903,
    name=_("Matter Group"),
    blurb=_("Common block"),
    shape=PENTAGON,
    scale=2,
    fillColor=0x222222,
    fillColor1=0x161515,
    lineColor=0x820a0a,
    durability=3,
},

{
    233346,
    group=17903,
    name=_("Matter Group"),
    blurb=_("Common block"),
    shape=ISOTRI_36,
    scale=2,
    fillColor=0x222222,
    fillColor1=0x161515,
    lineColor=0x820a0a,
    durability=3,
},

{
    233347,
    group=17903,
    name=_("Matter Group"),
    features=PALETTE,
    blurb=_("Common block"),
    shape=ISOTRI_36,
    scale=1,
    fillColor=0x222222,
    fillColor1=0x161515,
    lineColor=0x820a0a,
    durability=3,
},

{
    233348,
    group=17903,
    name=_("Matter Group"),
    blurb=_("Common block"),
    shape=ISOTRI_72,
    scale=1,
    fillColor=0x222222,
    fillColor1=0x161515,
    lineColor=0x820a0a,
    durability=3,
},

{
    233349,
    group=17903,
    name=_("Matter Group"),
    features=PALETTE,
    blurb=_("Common block"),
    shape=ISOTRI_72,
    scale=2,
    fillColor=0x222222,
    fillColor1=0x161515,
    lineColor=0x820a0a,
    durability=3,
},

{
    233350,
    group=17903,
    name=_("Matter Group"),
    blurb=_("Common block"),
    shape=RHOMBUS_36_144,
    scale=2,
    fillColor=0x222222,
    fillColor1=0x161515,
    lineColor=0x820a0a,
    durability=3,
},

{
    233351,
    group=17903,
    name=_("Matter Group"),
    blurb=_("Common block"),
    shape=RHOMBUS_36_144,
    scale=1,
    fillColor=0x222222,
    fillColor1=0x161515,
    lineColor=0x820a0a,
    durability=3,
},

{
    233352,
    group=17903,
    name=_("Matter Group"),
    blurb=_("Common block"),
    shape=RHOMBUS_72_108,
    scale=1,
    fillColor=0x222222,
    fillColor1=0x161515,
    lineColor=0x820a0a,
    durability=3,
},

{
    233353,
    group=17903,
    name=_("Matter Group"),
    blurb=_("Common block"),
    shape=RHOMBUS_72_108,
    scale=2,
    fillColor=0x222222,
    fillColor1=0x161515,
    lineColor=0x820a0a,
    durability=3,
},

{
    233354,
    group=17903,
    features=PALETTE|CANNON|TURRET,
    name=_("Burst Cannon"),
    blurb=_("Has a turret with a wide range of explosions"),
    shape=RHOMBUS_72_108,
    scale=1,
    fillColor=0x222222,
    fillColor1=0x161515,
    lineColor=0x820a0a,
    durability=3,
    cannon={
        damage=20,
        power=12,
        roundsPerSec=5,
        muzzleVel=900,
        range=1650,
        spread=0.05,
        color=0xa81818,
        explosive=ENABLED,
        explodeRadius=25,
    },
},

{
    233355,
    group=17903,
    features=PALETTE|CANNON|TURRET,
    name=_("Implosion Generator"),
    blurb=_("Small explosion range but high damage turret."),
    shape=RHOMBUS_72_108,
    scale=1,
    fillColor=0xa81818,
    fillColor1=0xa12b2b,
    lineColor=0x222222,
    durability=3,
    cannon={
        damage=50,
        power=10,
        roundsPerSec=5,
        muzzleVel=900,
        range=1650,
        spread=0.05,
        color=0x820a0a,
        explosive=ENABLED,
        explodeRadius=5,
    },
},

{
    233356,
    group=17903,
    features=PALETTE|LASER|TURRET,
    name=_("repair laser"),
    blurb=_("Can repair friendly ships quickly"),
    shape=PENTAGON,
    scale=1,
    fillColor=0xa81818,
    fillColor1=0xa12b2b,
    lineColor=0x222222,
    durability=3,
    shroud={
            {size={13,13},
             offset={1, 0, 0.2},
             taper=1, 
             count=1
             tri_color_id=1, 
             tri_color1_id=1,
             line_color_id=2, 
            angle=3.14,
            shape=PENTAGON,
             }
            {size={7,7},
             offset={1, 0, 0.3},
             taper=1, 
             count=1
             tri_color_id=1, 
             tri_color1_id=1,
             line_color_id=2, 
            angle=3.14,
            shape=PENTAGON,
             }
            {size={1,1},
             offset={1, -2, 0.35},
             taper=1, 
             count=1
             tri_color_id=2, 
             tri_color1_id=2,
             line_color_id=1, 
            angle=0,
            shape=PENTAGON,
             }
            {size={1,1},
             offset={1, 2, 0.35},
             taper=1, 
             count=1
             tri_color_id=2, 
             tri_color1_id=2,
             line_color_id=1, 
            angle=0,
            shape=PENTAGON,
             }
            {size={0.3,2},
             offset={0.8, 0, 0.32},
             taper=1, 
             count=1
             tri_color_id=1, 
             tri_color1_id=1,
             line_color_id=2, 
            angle=0,
            shape=SQUARE,
             }
            {size={0.5,0.5},
             offset={-1, 0, 0.32},
             taper=1, 
             count=1
             tri_color_id=2, 
             tri_color1_id=2,
             line_color_id=1, 
            angle=0,
            shape=NONAGON,
             }
            {size={0.5,0.5},
             offset={-1, 1, 0.32},
             taper=1, 
             count=1
             tri_color_id=2, 
             tri_color1_id=2,
             line_color_id=1, 
            angle=0,
            shape=NONAGON,
             }
            {size={0.5,0.5},
             offset={-1, -1, 0.32},
             taper=1, 
             count=1
             tri_color_id=2, 
             tri_color1_id=2,
             line_color_id=1, 
            angle=0,
            shape=NONAGON,
             }
            {size={12,3},
             offset={5, 4, 0.1},
             taper=1, 
             count=1
             tri_color_id=1, 
             tri_color1_id=1,
             line_color_id=2, 
            angle=0,
            shape=ADAPTER,
             }
            {size={12,3},
             offset={5, -4, 0.1},
             taper=1, 
             count=1
             tri_color_id=1, 
             tri_color1_id=1,
             line_color_id=2, 
            angle=0,
            shape=ADAPTER,
             }
            {size={1,5},
             offset={8, 2, 0.07},
             taper=5, 
             count=1
             tri_color_id=1, 
             tri_color1_id=1,
             line_color_id=2, 
            angle=0.2,
            shape=ADAPTER,
             }
            {size={1,5},
             offset={9.5, 2, 0.07},
             taper=5, 
             count=1
             tri_color_id=1, 
             tri_color1_id=1,
             line_color_id=2, 
            angle=0.2,
            shape=ADAPTER,
             }
            {size={1,5},
             offset={11, 2, 0.03},
             taper=5, 
             count=1
             tri_color_id=1, 
             tri_color1_id=1,
             line_color_id=2, 
            angle=0.2,
            shape=ADAPTER,
             }
            {size={3,2},
             offset={7, 1, 0.19},
             taper=5, 
             count=1
             tri_color_id=1, 
             tri_color1_id=1,
             line_color_id=2, 
            angle=0,
            shape=ADAPTER,
             }
            {size={3,1},
             offset={7, -1, 0.19},
             taper=5, 
             count=1
             tri_color_id=1, 
             tri_color1_id=1,
             line_color_id=2, 
            angle=0,
            shape=ADAPTER,
             }
            {size={0.8,1.2},
             offset={8.5, 1, 0.18},
             taper=5, 
             count=1
             tri_color_id=1, 
             tri_color1_id=1,
             line_color_id=2, 
            angle=0,
            shape=ADAPTER,
             }
            {size={1,5},
             offset={8, -2, 0.07},
             taper=5, 
             count=1
             tri_color_id=1, 
             tri_color1_id=1,
             line_color_id=2, 
            angle=-0.2,
            shape=ADAPTER,
             }
            {size={1,5},
             offset={9.5, -2, 0.07},
             taper=5, 
             count=1
             tri_color_id=1, 
             tri_color1_id=1,
             line_color_id=2, 
            angle=-0.2,
            shape=ADAPTER,
             }
            {size={1,5},
             offset={11, -2, 0.03},
             taper=5, 
             count=1
             tri_color_id=1, 
             tri_color1_id=1,
             line_color_id=2, 
            angle=-0.2,
            shape=ADAPTER,
             }
            {size={10,1.8},
             offset={10, -3.8, 0.05},
             taper=1, 
             count=1
             tri_color_id=1, 
             tri_color1_id=1,
             line_color_id=2, 
            angle=0.5,
            shape=TRI,
             }
            {size={10,1.8},
             offset={10, 3.8, 0.05},
             taper=1, 
             count=1
             tri_color_id=1, 
             tri_color1_id=1,
             line_color_id=2, 
            angle=-0.5,
            shape=TRI,
             }
            }
    laser={
        damage=-225,
        power=55,
        range=2000,
        width=3,
        color=0xa1d2d41a,
    },
},

{
    233357,
    group=17903,
    features=PALETTE|LASER|TURRET,
    name=_("repair laser"),
    blurb=_("Can repair friendly ships quickly"),
    shape=PENTAGON,
    scale=1,
    fillColor=0x222222,
    fillColor1=0x161515,
    lineColor=0x820a0a,
    durability=3,
    shroud={
            {size={13,13},
             offset={1, 0, 0.2},
             taper=1, 
             count=1
             tri_color_id=1, 
             tri_color1_id=1,
             line_color_id=2, 
            angle=3.14,
            shape=PENTAGON,
             }
            {size={7,7},
             offset={1, 0, 0.3},
             taper=1, 
             count=1
             tri_color_id=1, 
             tri_color1_id=1,
             line_color_id=2, 
            angle=3.14,
            shape=PENTAGON,
             }
            {size={1,1},
             offset={1, -2, 0.35},
             taper=1, 
             count=1
             tri_color_id=2, 
             tri_color1_id=2,
             line_color_id=1, 
            angle=0,
            shape=PENTAGON,
             }
            {size={1,1},
             offset={1, 2, 0.35},
             taper=1, 
             count=1
             tri_color_id=2, 
             tri_color1_id=2,
             line_color_id=1, 
            angle=0,
            shape=PENTAGON,
             }
            {size={0.3,2},
             offset={0.8, 0, 0.32},
             taper=1, 
             count=1
             tri_color_id=1, 
             tri_color1_id=1,
             line_color_id=2, 
            angle=0,
            shape=SQUARE,
             }
            {size={0.5,0.5},
             offset={-1, 0, 0.32},
             taper=1, 
             count=1
             tri_color_id=2, 
             tri_color1_id=2,
             line_color_id=1, 
            angle=0,
            shape=NONAGON,
             }
            {size={0.5,0.5},
             offset={-1, 1, 0.32},
             taper=1, 
             count=1
             tri_color_id=2, 
             tri_color1_id=2,
             line_color_id=1, 
            angle=0,
            shape=NONAGON,
             }
            {size={0.5,0.5},
             offset={-1, -1, 0.32},
             taper=1, 
             count=1
             tri_color_id=2, 
             tri_color1_id=2,
             line_color_id=1, 
            angle=0,
            shape=NONAGON,
             }
            {size={12,3},
             offset={5, 4, 0.1},
             taper=1, 
             count=1
             tri_color_id=1, 
             tri_color1_id=1,
             line_color_id=2, 
            angle=0,
            shape=ADAPTER,
             }
            {size={12,3},
             offset={5, -4, 0.1},
             taper=1, 
             count=1
             tri_color_id=1, 
             tri_color1_id=1,
             line_color_id=2, 
            angle=0,
            shape=ADAPTER,
             }
            {size={1,5},
             offset={8, 2, 0.07},
             taper=5, 
             count=1
             tri_color_id=1, 
             tri_color1_id=1,
             line_color_id=2, 
            angle=0.2,
            shape=ADAPTER,
             }
            {size={1,5},
             offset={9.5, 2, 0.07},
             taper=5, 
             count=1
             tri_color_id=1, 
             tri_color1_id=1,
             line_color_id=2, 
            angle=0.2,
            shape=ADAPTER,
             }
            {size={1,5},
             offset={11, 2, 0.03},
             taper=5, 
             count=1
             tri_color_id=1, 
             tri_color1_id=1,
             line_color_id=2, 
            angle=0.2,
            shape=ADAPTER,
             }
            {size={3,2},
             offset={7, 1, 0.19},
             taper=5, 
             count=1
             tri_color_id=1, 
             tri_color1_id=1,
             line_color_id=2, 
            angle=0,
            shape=ADAPTER,
             }
            {size={3,1},
             offset={7, -1, 0.19},
             taper=5, 
             count=1
             tri_color_id=1, 
             tri_color1_id=1,
             line_color_id=2, 
            angle=0,
            shape=ADAPTER,
             }
            {size={0.8,1.2},
             offset={8.5, 1, 0.18},
             taper=5, 
             count=1
             tri_color_id=1, 
             tri_color1_id=1,
             line_color_id=2, 
            angle=0,
            shape=ADAPTER,
             }
            {size={1,5},
             offset={8, -2, 0.07},
             taper=5, 
             count=1
             tri_color_id=1, 
             tri_color1_id=1,
             line_color_id=2, 
            angle=-0.2,
            shape=ADAPTER,
             }
            {size={1,5},
             offset={9.5, -2, 0.07},
             taper=5, 
             count=1
             tri_color_id=1, 
             tri_color1_id=1,
             line_color_id=2, 
            angle=-0.2,
            shape=ADAPTER,
             }
            {size={1,5},
             offset={11, -2, 0.03},
             taper=5, 
             count=1
             tri_color_id=1, 
             tri_color1_id=1,
             line_color_id=2, 
            angle=-0.2,
            shape=ADAPTER,
             }
            {size={10,1.8},
             offset={10, -3.8, 0.05},
             taper=1, 
             count=1
             tri_color_id=1, 
             tri_color1_id=1,
             line_color_id=2, 
            angle=0.5,
            shape=TRI,
             }
            {size={10,1.8},
             offset={10, 3.8, 0.05},
             taper=1, 
             count=1
             tri_color_id=1, 
             tri_color1_id=1,
             line_color_id=2, 
            angle=-0.5,
            shape=TRI,
             }
            }
    laser={
        damage=-225,
        power=55,
        range=2000,
        width=3,
        color=0xa1d2d41a,
    },
},

{
    233358,
    group=17903,
    features=PALETTE|AUTOFIRE|PALETTE|PALETTE|LASER|TURRET,
    name=_("Anti-missile laser"),
    blurb=_("Laser weapons that can effectively resist fast missiles"),
    shape=PENTAGON,
    scale=1,
    fillColor=0x222222,
    fillColor1=0x161515,
    lineColor=0x820a0a,
    durability=3,
    bindingId=5,
    shroud={
            {size={7,10},
             offset={1, 0, 0.01},
             taper=1, 
             count=1
             tri_color_id=1, 
             tri_color1_id=1,
             line_color_id=2, 
            angle=3.14,
            shape=TRI,
             }
            }
    laser={
        damage=300,
        power=60,
        range=1000,
        width=2,
        color=0xa1d2d41a,
    },
    turretSpeed=25,
},

{
    233359,
    group=17903,
    features=PALETTE|LAUNCHER,
    name=_("^1Light spot Summoner^7"),
    blurb=_("Emit the^5 light of the stars^7 that can be traced"),
    shape=RECT_LAUNCHER,
    scale=1,
    points=0,
    fillColor=0x222222,
    fillColor1=0x161515,
    lineColor=0x820a0a,
    durability=3,
    replicateBlock={
        group=17903,
        features=PALETTE|ALWAYSFIRE|CANNON|COMMAND|EXPLODE|GENERATOR|THRUSTER|TORQUER,
        name=_("^5 light of the stars"),
        blurb=_("A tracking unstable energy point that will bounce any enemy that doesn't belong to EOS."),
        shape=MISSILE,
        fillColor=0x820a0a,
        fillColor1=0xa12b2b,
        durability=4,
        lineColor=0x161515,
        lifetime=9,
        command={
        },
        points=3,
        generatorCapacityPerSec=400,
        powerCapacity=800,
        thrusterForce=3000,
        cannon={
            damage=25,
            power=1,
            recoil=0,
            projectileSize=5,
            roundsPerSec=200,
            range=10,
            muzzleVel=500,
            spread=3.14
            color=0x450000,
        },
        explodeDamage=20,
    },
    replicateTime=0.7,
    launcherPower=20,
    launcherOutSpeed=25,
},

{
    233361,
    group=17903,
    features=PALETTE|LAUNCHER,
    name=_("^1Light spot Summoner^7"),
    blurb=_("Emit the^5 light of the stars^7 that can be traced"),
    shape=RECT_LAUNCHER,
    scale=2,
    points=0,
    fillColor=0x222222,
    fillColor1=0x161515,
    lineColor=0x820a0a,
    durability=3,
    replicateBlock={
        group=17903,
        features=ALWAYSFIRE|CANNON|COMMAND|EXPLODE|GENERATOR|THRUSTER|TORQUER,
        name=_("^5 light of the stars"),
        blurb=_("A tracking unstable energy point that will bounce off any enemy that is not part of EOS."),
        shape=MISSILE,
        scale=2,
        fillColor=0x820a0a,
        fillColor1=0xa12b2b,
        lineColor=0xa12b2b,
        durability=4,
        lifetime=7,
        command={
        },
        points=3,
        generatorCapacityPerSec=400,
        powerCapacity=800,
        thrusterForce=3600,
        thrusterColor=0x5cff0000,
        thrusterColor1=0x94e58a8a,
        cannon={
            damage=55,
            power=1,
            range=10,
            recoil=0,
            projectileSize=15,
            roundsPerSec=200,
            muzzleVel=800,
            spread=3.14,
            color=0x55450000,
        },
        explodeDamage=200,
    },
    launcherPower=325,
    launcherOutSpeed=80,
},

{
    233363,
    group=17903,
    features=PALETTE|LASER|TURRET,
    name=_("Focused laser"),
    blurb=_("Firing high-intensity energy laser to burn the enemy's warships in an instant."),
    shape=PENTAGON,
    scale=2,
    fillColor=0xa12b2b,
    fillColor1=0x820a0a,
    lineColor=0x222222,
    durability=3,
    laser={
        damage=500,
        power=50,
        range=2000,
        width=4,
        color=0xa1a63333,
    },
    turretSpeed=25,
},

{
    233365,
    group=17903,
    features=PALETTE|CANNON|TURRET,
    name=_("Ion rapid-fire cannon"),
    blurb=_("Super turret with high rate of fire, bullet belt explosion."),
    shape=PENTAGON,
    scale=2,
    fillColor=0xa12b2b,
    fillColor1=0x820a0a,
    lineColor=0x222222,
    durability=2,
    barrelTaper=0
    shroud={
            {size={10,10},
             offset={1, 0, 0.2},
             taper=1, 
             count=1
             tri_color_id=2, 
             tri_color1_id=2,
             line_color_id=2, 
            angle=0,
            shape=TRI,
             }
            {size={10,10},
             offset={1, 5, 0.22},
             taper=1, 
             count=1
             tri_color_id=1, 
             tri_color1_id=1,
             line_color_id=2, 
            angle=0,
            shape=ADAPTER,
             }
            {size={10,10},
             offset={1, -5, 0.22},
             taper=1, 
             count=1
             tri_color_id=1, 
             tri_color1_id=1,
             line_color_id=2, 
            angle=0,
            shape=ADAPTER,
             }
            {size={20,20},
             offset={1, 0, 0.23},
             taper=1, 
             count=1
             tri_color_id=2, 
             tri_color1_id=2,
             line_color_id=1, 
            angle=0,
            shape=HEXAGON,
             }
            {size={2,2},
             offset={-7, 0, 0.3},
             taper=1, 
             count=2
             tri_color_id=2, 
             tri_color1_id=2,
             line_color_id=1, 
            angle=0,
            shape=HEXAGON,
             }
            {size={2,2},
             offset={9, 0, 0.3},
             taper=1, 
             count=2
             tri_color_id=2, 
             tri_color1_id=2,
             line_color_id=1, 
            angle=0,
            shape=HEXAGON,
             }
            {size={1,1},
             offset={-7, 0, 0.3},
             taper=1, 
             count=2
             tri_color_id=1, 
             tri_color1_id=1,
             line_color_id=2, 
            angle=0,
            shape=HEXAGON,
             }
            {size={25,10},
             offset={5, 8, 0.2},
             taper=1, 
             count=1
             tri_color_id=1, 
             tri_color1_id=1,
             line_color_id=2, 
            angle=0,
            shape=HEXAGON,
             }
            {size={25,5},
             offset={5, 9, 0.2},
             taper=1, 
             count=1
             tri_color_id=2, 
             tri_color1_id=2,
             line_color_id=1, 
            angle=0,
            shape=HEXAGON,
             }
            {size={25,5},
             offset={5, -9, 0.21},
             taper=1, 
             count=1
             tri_color_id=2, 
             tri_color1_id=2,
             line_color_id=1, 
            angle=0,
            shape=HEXAGON,
             }
            {size={25,10},
             offset={5, -8, 0.2},
             taper=1, 
             count=1
             tri_color_id=1, 
             tri_color1_id=1,
             line_color_id=2, 
            angle=0,
            shape=HEXAGON,
             }
            {size={35,3},
             offset={14, 0, 0.2},
             taper=1, 
             count=3
             tri_color_id=2, 
             tri_color1_id=2,
             line_color_id=1, 
            angle=0,
            shape=ADAPTER,
             }
            {size={0.4,8},
             offset={1, -0.2, 0.29},
             taper=1, 
             count=2
             tri_color_id=1, 
             tri_color1_id=1,
             line_color_id=2, 
            angle=1.58,
            shape=SQUARE,
             }
            {size={1,1},
             offset={9, 0, 0.3},
             taper=1, 
             count=2
             tri_color_id=1, 
             tri_color1_id=1,
             line_color_id=2, 
            angle=0,
            shape=HEXAGON,
             }
            }
    cannon={
        damage=30,
        power=10,
        roundsPerSec=50,
        muzzleVel=900,
        range=1700,
        spread=0.1,
        color=0x820a0a,
        explosive=ENABLED,
        explodeRadius=20,
    },
    turretSpeed=25,
},

{
    233366,
    group=17903,
    features=PALETTE|THRUSTER,
    name=_("Arauco Thruster"),
    blurb=_("A propulsion module that can increase the speed of a ship."),
    shape=THRUSTER_PENT,
    fillColor=0xa12b2b,
    fillColor1=0xa81818,
    lineColor=0x161515,
    thrusterForce=70000,
    thrusterColor=0xff722222,
    thrusterColor1=0x7aab4141,
},

{
    233367,
    group=17903,
    features=PALETTE|THRUSTER,
    name=_("Arauco Thruster"),
    blurb=_("A propulsion module that can increase the speed of a ship."),
    shape=THRUSTER_PENT,
    scale=2,
    fillColor=0xa12b2b,
    fillColor1=0xa81818,
    lineColor=0x161515,
    thrusterForce=125000,
    thrusterColor=0xff722222,
    thrusterColor1=0x7aab4141,
},

{
    233368,
    group=17903,
    features=PALETTE|THRUSTER,
    name=_("Arauco Thruster"),
    blurb=_("A propulsion module that can increase the speed of a ship."),
    shape=THRUSTER_PENT,
    scale=3,
    fillColor=0xa12b2b,
    fillColor1=0xa81818,
    lineColor=0x161515,
    thrusterForce=400000,
    thrusterColor=0xff722222,
    thrusterColor1=0x7aab4141,
},

{
    233369,
    group=17903,
    features=PALETTE|THRUSTER,
    name=_("Arauco Thruster"),
    blurb=_("A propulsion module that can increase the speed of a ship."),
    shape=THRUSTER_PENT,
    scale=3,
    fillColor=0x161515,
    fillColor1=0x222222,
    lineColor=0x820a0a,
    thrusterForce=400000,
    thrusterColor=0xff722222,
    thrusterColor1=0x7aab4141,
},

{
    233370,
    group=17903,
    features=PALETTE|THRUSTER,
    name=_("Arauco Thruster"),
    blurb=_("A propulsion module that can increase the speed of a ship."),
    shape=THRUSTER_PENT,
    scale=2,
    fillColor=0x161515,
    fillColor1=0x222222,
    lineColor=0x820a0a,
    thrusterForce=125000,
    thrusterColor=0xff722222,
    thrusterColor1=0x7aab4141,
},

{
    233371,
    group=17903,
    features=PALETTE|THRUSTER,
    name=_("Arauco Thruster"),
    blurb=_("A propulsion module that can increase the speed of a ship."),
    shape=THRUSTER_PENT,
    scale=1,
    fillColor=0x161515,
    fillColor1=0x222222,
    lineColor=0x820a0a,
    thrusterForce=70000,
    thrusterColor=0xff722222,
    thrusterColor1=0x7aab4141,
},

{
    233372,
    group=17903,
    features=PALETTE|GENERATOR,
    name=_("Generator"),
    blurb=_("Generate electricity for ships."),
    shape=RHOMBUS_72_108,
    fillColor=0x161515,
    fillColor1=0x222222,
    lineColor=0xa81818,
    generatorCapacityPerSec=200,
    powerCapacity=500,
},

{
    233373,
    group=17903,
    features=PALETTE|FACTORY,
    name=_("Summon Station"),
    blurb=_("summon ships."),
    shape=RHOMBUS_72_108,
    scale=2,
    fillColor=0xa81818,
    fillColor1=0xa12b2b,
    lineColor=0x222222,
    durability=3,
    capacity=500,
},

{
    233374,
    group=17903,
    features=PALETTE,
    name=_("Adaptation Matter Group"),
    shape=ADAPTER,
    fillColor=0xa12b2b,
    fillColor1=0xa81818,
    lineColor=0x222222,
    durability=3,
},

{
    233375,
    group=17903,
    name=_("Adaptation Matter Group"),
    shape=ADAPTER,
    scale=2,
    fillColor=0xa12b2b,
    fillColor1=0xa81818,
    lineColor=0x222222,
    durability=3,
},

{
    233376,
    group=17903,
    name=_("Adaptation Matter Group"),
    shape=ADAPTER,
    scale=3,
    fillColor=0xa12b2b,
    fillColor1=0xa81818,
    lineColor=0x222222,
    durability=3,
},

{
    233377,
    group=17903,
    name=_("Adaptation Matter Group"),
    shape=ADAPTER,
    scale=3,
    fillColor=0x161515,
    fillColor1=0x222222,
    lineColor=0x820a0a,
    durability=3,
},

{
    233378,
    group=17903,
    name=_("Adaptation Matter Group"),
    shape=ADAPTER,
    scale=2,
    fillColor=0x161515,
    fillColor1=0x222222,
    lineColor=0x820a0a,
    durability=3,
},

{
    233379,
    group=17903,
    features=PALETTE,
    name=_("Adaptation Matter Group"),
    shape=ADAPTER,
    scale=1,
    fillColor=0x161515,
    fillColor1=0x222222,
    lineColor=0x820a0a,
    durability=3,
},

{
    233380,
    group=17903,
    features=PALETTE|CANNON|TURRET,
    name=_("High Explosive Cannon"),
    blurb=_("A large turret that fires a projectile that can produce a wide range of explosions."),
    shape=RHOMBUS_72_108,
    scale=2,
    fillColor=0x820a0a,
    fillColor1=0xa12b2b,
    lineColor=0x222222,
    cannon={
        damage=20,
        power=50,
        roundsPerSec=10,
        muzzleVel=800,
        range=2000,
        spread=0.12,
        color=0x9e2f2f,
        explosive=ENABLED,
        explodeRadius=50,
    },
},

{
    233381,
    group=17903,
    features=PALETTE|CANNON|TURRET,
    name=_("Super Implosion Generator"),
    blurb=_("A large turret that fires small but high damage explosive bullets."),
    shape=RHOMBUS_72_108,
    scale=2,
    fillColor=0x161515,
    fillColor1=0x222222,
    lineColor=0x820a0a,
    cannon={
        damage=80,
        power=30,
        roundsPerSec=15,
        muzzleVel=800,
        range=2000,
        spread=0.12,
        color=0x9e2f2f,
        explosive=ENABLED,
        explodeRadius=10,
    },
},

{
    233382,
    group=17903,
    features=PALETTE|GENERATOR,
    name=_("capacitor"),
    blurb=_("Advanced capacitors, which store electricity, but need to consume power to provide energy"),
    shape=RHOMBUS_72_108,
    fillColor=0x161515,
    fillColor1=0x222222,
    lineColor=0xa12b2b,
    points=5,
    durability=2,
    density=0.3,
    growRate=2,
    capacity=500,
    generatorCapacityPerSec=-50,
    powerCapacity=1500,
},

{
    233383,
    group=17903,
    features=PALETTE|GENERATOR,
    name=_("capacitor"),
    blurb=_("Advanced capacitors, which store electricity, but need to consume power to provide energy"),
    shape=RHOMBUS_36_144,
    fillColor=0x161515,
    fillColor1=0x222222,
    lineColor=0xa12b2b,
    points=5,
    durability=2,
    density=0.3,
    growRate=2,
    capacity=500,
    generatorCapacityPerSec=-50,
    powerCapacity=1500,
},

{
    233384,
    group=17903,
    features=PALETTE|LASER,
    name=_("Curved light blade"),
    blurb=_("Super war blade that can easily cut the armor of a warship."),
    shape=ISOTRI_36,
    fillColor=0x161515,
    fillColor1=0x222222,
    lineColor=0xa12b2b,
    points=0,
    durability=2,
    density=0.3,
    growRate=2,
    capacity=500,
    laser={
        damage=12500,
        power=50,
        range=235,
        width=4,
        color=0xb8c02828,
        decay=0.7,
    },
},

{
    233385,
    group=17903,
    features=PALETTE|TRACTOR,
    name=_("Tractor"),
    blurb=_("Collect resources and store them"),
    shape=RHOMBUS_72_108,
    fillColor=0x820a0a,
    fillColor1=0xa12b2b,
    lineColor=0x222222,
    capacity=4000,
    tractorRange=800,
},
